# -*- coding: utf-8 -*-
"""project-103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1airEe77vfd6wOqgIGFlyCyfWaAI--NeW
"""

from google.colab import files
data_to_load=files.upload()

import plotly.express as px
import pandas as pd

data= pd.read_csv("Copy+of+data+-+data (1).csv")
fig=px.bar(data, x="date", y="cases",color="country")
fig.show()